#########################################################################
# This script has been modified from the the auto-generated script made by "makeShinyAppV4.R".
# The edits contained in this script support the following new 
# functions:
# 1. Auto-detection of local or SciLifeLab app launching.
# 2. Cell Type Mode addition to heatmap/bubblepot for merged and immune. 
#########################################################################


library(shiny) 
library(shinyhelper) 
library(data.table) 
library(Matrix) 
library(DT) 
library(magrittr) 
library(ggplot2) 
library(ggrepel) 
library(hdf5r) 
library(ggdendro) 
library(grid) 
library(gridExtra) 


#########################################################################
# Manual Edit 01
# Auto-detection of local or SciLifeLab app launching.
# Every instance of "merged_objassay_" or "immune_objassay_" must be 
# replaced by the variables merged_h5 or immune_h5 manually.
#########################################################################


#### auto-detect environment (this was updated by Emma Bolech after the script was generated by "makeShinyAppV4.R") ####
data_path <- if (file.exists("./merged_objconf.rds")) {
  "./"
} else if (file.exists("/srv/shiny-server/data/merged_objconf.rds")) {
  "/srv/shiny-server/data/"
} else {
  stop("Data not found in either local or mounted path")
}

#### also updated by Emma Bolech (every insance of the auto generated "merged_objassay_" in the script was replaced with the variable merged_h5 and same for "immune_objassay_" to immune_h5) ####
merged_h5 <- paste0(data_path, "merged_objassay_")  
immune_h5 <- paste0(data_path, "immune_objassay_")

#### the file paths here were updated by Emma Bolech after the script was generated ####
merged_objconf = readRDS(paste0(data_path, "merged_objconf.rds"))
merged_objmeta = readRDS(paste0(data_path, "merged_objmeta.rds"))
merged_objgene = readRDS(paste0(data_path,"merged_objgene.rds"))
merged_objdimr = readRDS(paste0(data_path,"merged_objdimr.rds"))
merged_objdef  = readRDS(paste0(data_path,"merged_objdef.rds"))
immune_objconf = readRDS(paste0(data_path,"immune_objconf.rds"))
immune_objmeta = readRDS(paste0(data_path,"immune_objmeta.rds"))
immune_objgene = readRDS(paste0(data_path,"immune_objgene.rds"))
immune_objdimr = readRDS(paste0(data_path,"immune_objdimr.rds"))
immune_objdef  = readRDS(paste0(data_path,"immune_objdef.rds"))
source("./shinyFunc.R")
pdf(file = NULL)

#########################################################################
#########################################################################


### Useful stuff 
# Colour palette 
cList = list(c("grey85","#FFF7EC","#FEE8C8","#FDD49E","#FDBB84", 
               "#FC8D59","#EF6548","#D7301F","#B30000","#7F0000"), 
             c("#4575B4","#74ADD1","#ABD9E9","#E0F3F8","#FFFFBF", 
               "#FEE090","#FDAE61","#F46D43","#D73027")[c(1,1:9,9)], 
             c("#FDE725","#AADC32","#5DC863","#27AD81","#21908C", 
               "#2C728E","#3B528B","#472D7B","#440154")) 
names(cList) = c("White-Red", "Blue-Yellow-Red", "Yellow-Green-Purple") 

# Panel sizes 
pList = c("400px", "600px", "800px") 
names(pList) = c("Small", "Medium", "Large") 
pList2 = c("500px", "700px", "900px") 
names(pList2) = c("Small", "Medium", "Large") 
pList3 = c("600px", "800px", "1000px") 
names(pList3) = c("Small", "Medium", "Large") 
sList = c(18,24,30)
names(sList) = c("Small", "Medium", "Large") 



### Start server code 
shinyServer(function(input, output, session) { 
  ### For all tags and Server-side selectize 
  observe_helpers() 
  optCrt="{ option_create: function(data,escape) {return('<div class=\"create\"><strong>' + '</strong></div>');} }" 
  observe({ 
    invalidateLater(30000) # ping every 30 seconds to keep connection alive 
    cat(".") 
  }) 

### Functions for tab A1 
getGmerged_obja1inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$merged_obja1ass1)) 
  if(gsub("^Assay: ", "", input$merged_obja1ass1) == "Cell Information"){ 
    res <- merged_objconf$UI 
    resDef <- merged_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(merged_objgene[[gsub("^Assay: ", "", input$merged_obja1ass1)]]) 
    resDef <- merged_objdef$gene1[[gsub("^Assay: ", "", input$merged_obja1ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$merged_obja1ass1), {
  updateSelectizeInput(session, "merged_obja1inp1", choices = getGmerged_obja1inp1()[[1]], 
                       server = TRUE, selected = getGmerged_obja1inp1()[[2]], options = list( 
                         maxOptions = getGmerged_obja1inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
output$merged_obja1sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_obja1sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_obja1sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_obja1sub1non, { 
  sub = strsplit(merged_objconf[UI == input$merged_obja1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_obja1sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$merged_obja1sub1all, { 
  sub = strsplit(merged_objconf[UI == input$merged_obja1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_obja1sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

merged_obja1oup1xy <- reactiveValues(x = NULL, y = NULL)
observe({
  brush <- input$merged_obja1inp1.br
  if (!is.null(brush)) {
    merged_obja1oup1xy$x <- c(brush$xmin, brush$xmax)
    merged_obja1oup1xy$y <- c(brush$ymin, brush$ymax)
  } else {
    merged_obja1oup1xy$x <- NULL; merged_obja1oup1xy$y <- NULL
  }
})
merged_obja1oup1br <- reactive({
  sc2Ddimr(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja1dr, input$merged_obja1inp1,
           merged_h5, merged_objgene, input$merged_obja1ass1, input$merged_obja1sub1, input$merged_obja1sub2,  
           input$merged_obja1min1, input$merged_obja1max1, input$merged_obja1siz/2, input$merged_obja1ord1,
           cList[[input$merged_obja1col1]], sList[input$merged_obja1fsz]/2, 
           input$merged_obja1asp, FALSE, FALSE) 
})
output$merged_obja1oup1.br <- renderPlot({merged_obja1oup1br() + theme(legend.position = "none")}) 

merged_obja1oup1 <- reactive({
  sc2Ddimr(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja1dr, input$merged_obja1inp1,
           merged_h5, merged_objgene, input$merged_obja1ass1, input$merged_obja1sub1, input$merged_obja1sub2,  
           input$merged_obja1min1, input$merged_obja1max1, input$merged_obja1siz, input$merged_obja1ord1,
           cList[[input$merged_obja1col1]], sList[input$merged_obja1fsz], 
           input$merged_obja1asp, input$merged_obja1txt, input$merged_obja1lab1)
})
output$merged_obja1oup1 <- renderPlot({
  if(is.null(merged_obja1oup1xy$x[1])){
    merged_obja1oup1() + theme(legend.position = "none")
  } else {
    merged_obja1oup1() + theme(legend.position = "none") + 
      scale_x_continuous(limits = merged_obja1oup1xy$x, expand = c(0, 0)) + 
      scale_y_continuous(limits = merged_obja1oup1xy$y, expand = c(0, 0)) 
  }
})
output$merged_obja1oup1.ui <- renderUI({plotOutput("merged_obja1oup1", height = pList[input$merged_obja1psz])})
output$merged_obja1oup1.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja1dr,"_",input$merged_obja1inp1,".",input$merged_obja1oup1.f) },
  content = function(file) { 
    if(is.null(merged_obja1oup1xy$x[1])){
      ggsav(file, height = input$merged_obja1oup1.h, width = input$merged_obja1oup1.w, 
            plot = merged_obja1oup1() + theme(legend.position = "none"))
    } else {
      ggsav(file, height = input$merged_obja1oup1.h, width = input$merged_obja1oup1.w, 
            plot = merged_obja1oup1() + theme(legend.position = "none") + 
              scale_x_continuous(limits = merged_obja1oup1xy$x, expand = c(0, 0)) + 
              scale_y_continuous(limits = merged_obja1oup1xy$y, expand = c(0, 0)))
    }
})
output$merged_obja1oup3 <- renderPlot({grid.newpage(); grid.draw(g_legend(merged_obja1oup1()))})
output$merged_obja1oup3.ui <- renderUI({plotOutput("merged_obja1oup3", height = 72*convertHeight(
  grobHeight(g_legend(merged_obja1oup1())), unitTo="in", valueOnly=TRUE) + 50)})
output$merged_obja1oup3.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja1dr,"_",input$merged_obja1inp1,"_leg.",input$merged_obja1oup3.f) },
  content = function(file) { 
    grid.newpage(); grid.draw(g_legend(merged_obja1oup1()))
    ggsav(file, height = input$merged_obja1oup3.h, width = input$merged_obja1oup3.w, plot = grid.grab())
}) 

output$merged_obja1.dt <- renderDataTable({
  ggData = sc2Dnum(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja1dr, merged_obja1oup1xy$x, merged_obja1oup1xy$y, input$merged_obja1inp1,
                   merged_h5, merged_objgene, input$merged_obja1ass1, input$merged_obja1sub1, input$merged_obja1sub2, input$merged_obja1splt)
  datatable(ggData, rownames = FALSE, extensions = "Buttons",
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>%
    formatRound(columns = c("pctZoom"), digits = 2)
})


### Functions for tab A2 
getGmerged_obja2inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$merged_obja2ass1)) 
  if(gsub("^Assay: ", "", input$merged_obja2ass1) == "Cell Information"){ 
    res <- merged_objconf$UI 
    resDef <- merged_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(merged_objgene[[gsub("^Assay: ", "", input$merged_obja2ass1)]]) 
    resDef <- merged_objdef$gene1[[gsub("^Assay: ", "", input$merged_obja2ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$merged_obja2ass1), {
  updateSelectizeInput(session, "merged_obja2inp1", choices = getGmerged_obja2inp1()[[1]], 
                       server = TRUE, selected = getGmerged_obja2inp1()[[2]], options = list( 
                         maxOptions = getGmerged_obja2inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
getGmerged_obja2inp2 <- reactive({ 
  req(gsub("^Assay: ", "", input$merged_obja2ass2)) 
  if(gsub("^Assay: ", "", input$merged_obja2ass2) == "Cell Information"){ 
    res <- merged_objconf$UI 
    resDef <- merged_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(merged_objgene[[gsub("^Assay: ", "", input$merged_obja2ass2)]]) 
    resDef <- merged_objdef$gene1[[gsub("^Assay: ", "", input$merged_obja2ass2)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$merged_obja2ass2), {
  updateSelectizeInput(session, "merged_obja2inp2", choices = getGmerged_obja2inp2()[[1]], 
                       server = TRUE, selected = getGmerged_obja2inp2()[[2]], options = list( 
                         maxOptions = getGmerged_obja2inp2()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
  output$merged_obja2sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_obja2sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_obja2sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_obja2sub1non, {
  sub = strsplit(merged_objconf[UI == input$merged_obja2sub1]$fID, "\\|")[[1]]
  updateCheckboxGroupInput(session, inputId = "merged_obja2sub2", label = "Select which cells to show",
                           choices = sub, selected = NULL, inline = TRUE)
})
observeEvent(input$merged_obja2sub1all, {
  sub = strsplit(merged_objconf[UI == input$merged_obja2sub1]$fID, "\\|")[[1]]
  updateCheckboxGroupInput(session, inputId = "merged_obja2sub2", label = "Select which cells to show",
                           choices = sub, selected = sub, inline = TRUE)
})

merged_obja2oup1 <- reactive({
  sc2Ddimr(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja2dr, input$merged_obja2inp1,
           merged_h5, merged_objgene, input$merged_obja2ass1, input$merged_obja2sub1, input$merged_obja2sub2,  
           input$merged_obja2min1, input$merged_obja2max1, input$merged_obja2siz, input$merged_obja2ord1,
           cList[[input$merged_obja2col1]], sList[input$merged_obja2fsz], 
           input$merged_obja2asp, input$merged_obja2txt, input$merged_obja2lab1) 
})
output$merged_obja2oup1 <- renderPlot({merged_obja2oup1() + theme(legend.position = "none")})
output$merged_obja2oup1.ui <- renderUI({plotOutput("merged_obja2oup1", height = pList[input$merged_obja2psz])})
output$merged_obja2oup1.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja2dr,"_",input$merged_obja2inp1,".",input$merged_obja2oup1.f) },
  content = function(file) { ggsav(file, height = input$merged_obja2oup1.h, width = input$merged_obja2oup1.w, 
                                   plot = merged_obja2oup1() + theme(legend.position = "none"))
})
output$merged_obja2oup3 <- renderPlot({grid.newpage(); grid.draw(g_legend(merged_obja2oup1()))})
output$merged_obja2oup3.ui <- renderUI({plotOutput("merged_obja2oup3", height = 72*convertHeight(
  grobHeight(g_legend(merged_obja2oup1())), unitTo="in", valueOnly=TRUE) + 50)})
output$merged_obja2oup3.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja2dr,"_",input$merged_obja2inp1,"_leg.",input$merged_obja2oup3.f) },
content = function(file) { 
  grid.newpage(); grid.draw(g_legend(merged_obja2oup1()))
  ggsav(file, height = input$merged_obja2oup3.h, width = input$merged_obja2oup3.w, plot = grid.grab())
})

merged_obja2oup2 <- reactive({
  sc2Ddimr(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja2dr, input$merged_obja2inp2,
           merged_h5, merged_objgene, input$merged_obja2ass2, input$merged_obja2sub1, input$merged_obja2sub2,  
           input$merged_obja2min2, input$merged_obja2max2, input$merged_obja2siz, input$merged_obja2ord2,
           cList[[input$merged_obja2col2]], sList[input$merged_obja2fsz], 
           input$merged_obja2asp, input$merged_obja2txt, input$merged_obja2lab2) 
})
output$merged_obja2oup2 <- renderPlot({merged_obja2oup2() + theme(legend.position = "none")})
output$merged_obja2oup2.ui <- renderUI({plotOutput("merged_obja2oup2", height = pList[input$merged_obja2psz])})
output$merged_obja2oup2.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja2dr,"_",input$merged_obja2inp2,".",input$merged_obja2oup2.f) },
  content = function(file) { ggsav(file, height = input$merged_obja2oup2.h, width = input$merged_obja2oup2.w, 
                                   plot = merged_obja2oup2() + theme(legend.position = "none"))
})

output$merged_obja2oup4 <- renderPlot({grid.newpage(); grid.draw(g_legend(merged_obja2oup2()))})
output$merged_obja2oup4.ui <- renderUI({plotOutput("merged_obja2oup4", height = 72*convertHeight(
  grobHeight(g_legend(merged_obja2oup2())), unitTo="in", valueOnly=TRUE) + 50)})
output$merged_obja2oup4.dl <- downloadHandler(
  filename = function() { paste0("merged_obj",input$merged_obja2dr,"_",input$merged_obja2inp2,"_leg.",input$merged_obja2oup4.f) },
content = function(file) { 
  grid.newpage(); grid.draw(g_legend(merged_obja2oup2()))
  ggsav(file, height = input$merged_obja2oup4.h, width = input$merged_obja2oup4.w, plot = grid.grab())
})

merged_obja2oup5 <- reactive({
  sc2Dcomp(merged_objconf, merged_objmeta, input$merged_obja2inp1, input$merged_obja2inp2,
           merged_h5, merged_objgene, input$merged_obja2ass1, input$merged_obja2ass2, input$merged_obja2sub1, input$merged_obja2sub2,
           input$merged_obja2min1, input$merged_obja2max1, input$merged_obja2min2, input$merged_obja2max2, 
           input$merged_obja2siz, cList[[input$merged_obja2col2]], sList[input$merged_obja2fsz]) 
})
output$merged_obja2oup5 <- renderPlot({merged_obja2oup5() + theme(legend.position = "none")})
output$merged_obja2oup5.ui <- renderUI({plotOutput("merged_obja2oup5", height = pList[input$merged_obja2psz])})
output$merged_obja2oup5.dl <- downloadHandler( 
  filename = function() { paste0("merged_objcompare_",input$merged_obja2inp1,"_",input$merged_obja2inp2,".",input$merged_obja2oup5.f) }, 
  content = function(file) { ggsav(file, height = input$merged_obja2oup5.h, width = input$merged_obja2oup5.w, 
                                   plot = merged_obja2oup5()) 
}) 
output$merged_obja2.dt <- renderDataTable({
  ggData = sc2Dcnum(merged_objconf, merged_objmeta, input$merged_obja2inp1, input$merged_obja2inp2,
                    merged_h5, merged_objgene, input$merged_obja2ass1, input$merged_obja2ass2, input$merged_obja2sub1, input$merged_obja2sub2,
                    input$merged_obja2min1, input$merged_obja2max1, input$merged_obja2min2, input$merged_obja2max2, input$merged_obja2cut)
  datatable(ggData, rownames = FALSE, extensions = "Buttons",
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel")))
})


### Functions for tab A3 
getGmerged_obja3inp1 <- reactive({ 
  req(input$merged_obja3ass1) 
  res <- names(merged_objgene[[input$merged_obja3ass1]]) 
  resDef1 <- merged_objdef$gene1[[input$merged_obja3ass1]] 
  resDef2 <- merged_objdef$gene2[[input$merged_obja3ass1]] 
  return(list(res,resDef1,resDef2))
})
observeEvent(input$merged_obja3ass1, {
  updateSelectizeInput(session, "merged_obja3inp1", choices = getGmerged_obja3inp1()[[1]], 
                       server = TRUE, selected = getGmerged_obja3inp1()[[2]], options = list( 
                         maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) 
})
observeEvent(input$merged_obja3ass1, {
  updateSelectizeInput(session, "merged_obja3inp2", choices = getGmerged_obja3inp1()[[1]], 
                       server = TRUE, selected = getGmerged_obja3inp1()[[3]], options = list( 
                         maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) 
})
output$merged_obja3sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_obja3sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_obja3sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_obja3sub1non, { 
  sub = strsplit(merged_objconf[UI == input$merged_obja3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_obja3sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$merged_obja3sub1all, { 
  sub = strsplit(merged_objconf[UI == input$merged_obja3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_obja3sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 
merged_obja3oup1 <- reactive({
  scDRcoex(merged_objconf, merged_objmeta, merged_objdimr, input$merged_obja3dr, input$merged_obja3inp1, input$merged_obja3inp2, 
           paste0(merged_h5, input$merged_obja3ass1, ".h5"), merged_objgene[[input$merged_obja3ass1]], 
           input$merged_obja3sub1, input$merged_obja3sub2, input$merged_obja3min1, input$merged_obja3max1, input$merged_obja3min2, input$merged_obja3max2, 
           input$merged_obja3siz, input$merged_obja3col1, input$merged_obja3ord1, 
           sList[input$merged_obja3fsz], input$merged_obja3asp, input$merged_obja3txt) 
}) 
output$merged_obja3oup1 <- renderPlot({merged_obja3oup1()}) 
output$merged_obja3oup1.ui <- renderUI({plotOutput("merged_obja3oup1", height = pList2[input$merged_obja3psz])}) 
output$merged_obja3oup1.dl <- downloadHandler( 
  filename = function() { paste0("merged_obj",input$merged_obja3dr,"_",input$merged_obja3inp1,"_",input$merged_obja3inp2,".",input$merged_obja3oup1.f) }, 
  content = function(file) { ggsav(file, height = input$merged_obja3oup1.h, width = input$merged_obja3oup1.w, plot = merged_obja3oup1())
}) 

output$merged_obja3oup2 <- renderPlot({scDRcoexLeg(input$merged_obja3inp1, input$merged_obja3inp2, input$merged_obja3col1, sList[input$merged_obja3fsz])}) 
output$merged_obja3oup2.ui <- renderUI({plotOutput("merged_obja3oup2", height = "300px")})
output$merged_obja3oup2.dl <- downloadHandler( 
  filename = function() { paste0("merged_obj",input$merged_obja3dr,"_",input$merged_obja3inp1,"_",input$merged_obja3inp2,"_leg.",input$merged_obja3oup2.f) }, 
  content = function(file) { ggsav(file, height = 3, width = 4, 
                                   plot = scDRcoexLeg(input$merged_obja3inp1, input$merged_obja3inp2, input$merged_obja3col1, sList[input$merged_obja3fsz]))
}) 
output$merged_obja3.dt <- renderDataTable({ 
  ggData = scDRcoexNum(merged_objconf, merged_objmeta, input$merged_obja3inp1, input$merged_obja3inp2, 
                       paste0(merged_h5, input$merged_obja3ass1, ".h5"), merged_objgene[[input$merged_obja3ass1]], 
                       input$merged_obja3sub1, input$merged_obja3sub2) 
  datatable(ggData, rownames = FALSE, extensions = "Buttons", 
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>% 
    formatRound(columns = c("percent"), digits = 2) 
}) 


### Functions for tab B1 
getGmerged_objb1inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$merged_objb1ass1)) 
  if(gsub("^Assay: ", "", input$merged_objb1ass1) == "Cell Information"){ 
    res <- merged_objconf[is.na(fID)]$UI 
    resDef <- merged_objconf[is.na(fID)]$UI[1] 
    resLen <- length(res) 
  } else { 
    res <- names(merged_objgene[[gsub("^Assay: ", "", input$merged_objb1ass1)]]) 
    resDef <- merged_objdef$gene1[[gsub("^Assay: ", "", input$merged_objb1ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$merged_objb1ass1), {
  updateSelectizeInput(session, "merged_objb1inp2", choices = getGmerged_objb1inp1()[[1]], 
                       server = TRUE, selected = getGmerged_objb1inp1()[[2]], options = list( 
                         maxOptions = getGmerged_objb1inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
output$merged_objb1sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_objb1sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_objb1sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_objb1sub1non, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb1sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$merged_objb1sub1all, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb1sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

merged_objb1oup <- reactive({
  scVioBox(merged_objconf, merged_objmeta, input$merged_objb1inp1, input$merged_objb1inp2, 
           merged_h5, merged_objgene, input$merged_objb1ass1, 
           input$merged_objb1sub1, input$merged_objb1sub2, input$merged_objb1typ, input$merged_objb1pts, 
           input$merged_objb1stg, input$merged_objb1stp1, input$merged_objb1stp2, 
           input$merged_objb1siz, sList[input$merged_objb1fsz], input$merged_objb1noi) 
}) 
output$merged_objb1oup <- renderPlot({merged_objb1oup()}) 
output$merged_objb1oup.ui <- renderUI({plotOutput("merged_objb1oup", height = pList2[input$merged_objb1psz])}) 
output$merged_objb1oup.dl <- downloadHandler( 
  filename = function() { paste0("merged_obj",input$merged_objb1typ,"_",input$merged_objb1inp1,"_",input$merged_objb1inp2,".",input$merged_objb1oup.f) }, 
  content = function(file) { ggsave(file, height = input$merged_objb1oup.h, width = input$merged_objb1oup.w, plot = merged_objb1oup())
}) 


### Functions for tab B2 
observeEvent(input$merged_objb2inp1, {
  sub = strsplit(merged_objconf[UI == input$merged_objb2inp2]$fID, "\\|")[[1]] 
  updateSelectizeInput(session, "merged_objb2ord1", choices = c("Original order", sub), 
                       server = TRUE, selected = "Original order", options = list( 
                       create = TRUE, persist = TRUE, render = I(optCrt))) 
}) 
output$merged_objb2sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_objb2sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_objb2sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_objb2sub1non, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb2sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb2sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$merged_objb2sub1all, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb2sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb2sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

merged_objb2oup  <- reactive({
  scProp(merged_objconf, merged_objmeta, input$merged_objb2inp1, input$merged_objb2inp2,  
         input$merged_objb2sub1, input$merged_objb2sub2, input$merged_objb2ord1, input$merged_objb2ord2, 
         input$merged_objb2typ, input$merged_objb2flp, sList[input$merged_objb2fsz]) 
})
output$merged_objb2oup <- renderPlot({merged_objb2oup()}) 
output$merged_objb2oup.ui <- renderUI({plotOutput("merged_objb2oup", height = pList2[input$merged_objb2psz])}) 
output$merged_objb2oup.dl <- downloadHandler( 
  filename = function() { paste0("merged_obj",input$merged_objb2typ,"_",input$merged_objb2inp1,"_",input$merged_objb2inp2,".",input$merged_objb2oup.f) }, 
  content = function(file) { ggsave(file, height = input$merged_objb2oup.h, width = input$merged_objb2oup.w, plot = merged_objb2oup())
}) 


### Functions for tab B3 
getGmerged_objb3inp1 <- reactive({ 
  req(input$merged_objb3ass1) 
  resDef <- paste0(merged_objdef$genes[[input$merged_objb3ass1]], 
                   collapse = ", ") 
  return(resDef) 
}) 
observeEvent(input$merged_objb3ass1, { 
  updateTextAreaInput(session, "merged_objb3inp", value = getGmerged_objb3inp1()) 
}) 
output$merged_objb3sub1.ui <- renderUI({ 
  sub = strsplit(merged_objconf[UI == input$merged_objb3sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("merged_objb3sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$merged_objb3sub1non, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb3sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$merged_objb3sub1all, { 
  sub = strsplit(merged_objconf[UI == input$merged_objb3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "merged_objb3sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 
output$merged_objb3oupTxt <- renderUI({ 
  geneList = scGeneList(input$merged_objb3inp, merged_objgene[[input$merged_objb3ass1]]) 
  if(nrow(geneList) > 50){ 
    HTML("More than 50 input genes! Please reduce the gene list!") 
  } else { 
    oup = paste0(nrow(geneList[present == TRUE]), " genes OK and will be plotted") 
    if(nrow(geneList[present == FALSE]) > 0){ 
      oup = paste0(oup, "<br/>", 
                   nrow(geneList[present == FALSE]), " genes not found (", 
                   paste0(geneList[present == FALSE]$gene, collapse = ", "), ")") 
    } 
    HTML(oup) 
  } 
}) 
  
#########################################################################
# Manual Edit 02
# Cell Type Mode addition to heatmap/bubblepot. 
# Allows users to plot gene expression across batch/sample_id/timepoint
# for one selected celltype. 
#########################################################################

merged_objb3oup <- reactive({
  # this section was added to support switched between the default subsetting and the cell type mode
  if (input$merged_objb3_use_celltype) {   
    sub1 <- "annotated_celltype"                # subset by cell type annotation
    sub2 <- c(input$merged_objb3_celltype)      # selected cell type
    grp  <- input$merged_objb3_celltype_grp     # group by chosen variable
    scl  <- input$merged_objb3scl               # apply scaling if selected
  # otherwise do default subsetting
  } else {
    sub1 <- input$merged_objb3sub1
    sub2 <- input$merged_objb3sub2
    grp  <- input$merged_objb3grp
    scl  <- input$merged_objb3scl
  }

  # this section was added to catch and rename the error in cell type mode when not enough cell information is present
  # this prompts the user to try and remove the gene expression scaling
  tryCatch({

  scBubbHeat(merged_objconf, merged_objmeta, input$merged_objb3inp,
             grp, input$merged_objb3plt,
             paste0(merged_h5, input$merged_objb3ass1, ".h5"),
             merged_objgene[[input$merged_objb3ass1]],
             sub1, sub2, scl,
             input$merged_objb3row, input$merged_objb3col,
             cList[[input$merged_objb3cols]], sList[input$merged_objb3fsz],
             input$merged_objb3exp, input$merged_objb3max)
  
  # error catching as described above
  }, error = function(e) {
    if (grepl("NA/NaN/Inf", e$message)) {
      stop("Not enough cell information — try removing scaled expression or check for low-variance genes.")
    } else {
      stop(e)
    }
  }) 
})

  
#########################################################################
#########################################################################

  
  
output$merged_objb3oup <- renderPlot({merged_objb3oup()}) 
output$merged_objb3oup.ui <- renderUI({plotOutput("merged_objb3oup", height = pList3[input$merged_objb3psz])})
output$merged_objb3oup.dl <- downloadHandler( 
  filename = function() { paste0("merged_obj",input$merged_objb3plt,"_",input$merged_objb3grp,".",input$merged_objb3oup.f) }, 
  content = function(file) { ggsave(file, height = input$merged_objb3oup.h, width = input$merged_objb3oup.w, plot = merged_objb3oup())
}) 


### Functions for tab A1 
getGimmune_obja1inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$immune_obja1ass1)) 
  if(gsub("^Assay: ", "", input$immune_obja1ass1) == "Cell Information"){ 
    res <- immune_objconf$UI 
    resDef <- immune_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(immune_objgene[[gsub("^Assay: ", "", input$immune_obja1ass1)]]) 
    resDef <- immune_objdef$gene1[[gsub("^Assay: ", "", input$immune_obja1ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$immune_obja1ass1), {
  updateSelectizeInput(session, "immune_obja1inp1", choices = getGimmune_obja1inp1()[[1]], 
                       server = TRUE, selected = getGimmune_obja1inp1()[[2]], options = list( 
                         maxOptions = getGimmune_obja1inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
output$immune_obja1sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_obja1sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_obja1sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_obja1sub1non, { 
  sub = strsplit(immune_objconf[UI == input$immune_obja1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_obja1sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$immune_obja1sub1all, { 
  sub = strsplit(immune_objconf[UI == input$immune_obja1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_obja1sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

immune_obja1oup1xy <- reactiveValues(x = NULL, y = NULL)
observe({
  brush <- input$immune_obja1inp1.br
  if (!is.null(brush)) {
    immune_obja1oup1xy$x <- c(brush$xmin, brush$xmax)
    immune_obja1oup1xy$y <- c(brush$ymin, brush$ymax)
  } else {
    immune_obja1oup1xy$x <- NULL; immune_obja1oup1xy$y <- NULL
  }
})
immune_obja1oup1br <- reactive({
  sc2Ddimr(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja1dr, input$immune_obja1inp1,
           immune_h5, immune_objgene, input$immune_obja1ass1, input$immune_obja1sub1, input$immune_obja1sub2,  
           input$immune_obja1min1, input$immune_obja1max1, input$immune_obja1siz/2, input$immune_obja1ord1,
           cList[[input$immune_obja1col1]], sList[input$immune_obja1fsz]/2, 
           input$immune_obja1asp, FALSE, FALSE) 
})
output$immune_obja1oup1.br <- renderPlot({immune_obja1oup1br() + theme(legend.position = "none")}) 

immune_obja1oup1 <- reactive({
  sc2Ddimr(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja1dr, input$immune_obja1inp1,
           immune_h5, immune_objgene, input$immune_obja1ass1, input$immune_obja1sub1, input$immune_obja1sub2,  
           input$immune_obja1min1, input$immune_obja1max1, input$immune_obja1siz, input$immune_obja1ord1,
           cList[[input$immune_obja1col1]], sList[input$immune_obja1fsz], 
           input$immune_obja1asp, input$immune_obja1txt, input$immune_obja1lab1)
})
output$immune_obja1oup1 <- renderPlot({
  if(is.null(immune_obja1oup1xy$x[1])){
    immune_obja1oup1() + theme(legend.position = "none")
  } else {
    immune_obja1oup1() + theme(legend.position = "none") + 
      scale_x_continuous(limits = immune_obja1oup1xy$x, expand = c(0, 0)) + 
      scale_y_continuous(limits = immune_obja1oup1xy$y, expand = c(0, 0)) 
  }
})
output$immune_obja1oup1.ui <- renderUI({plotOutput("immune_obja1oup1", height = pList[input$immune_obja1psz])})
output$immune_obja1oup1.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja1dr,"_",input$immune_obja1inp1,".",input$immune_obja1oup1.f) },
  content = function(file) { 
    if(is.null(immune_obja1oup1xy$x[1])){
      ggsav(file, height = input$immune_obja1oup1.h, width = input$immune_obja1oup1.w, 
            plot = immune_obja1oup1() + theme(legend.position = "none"))
    } else {
      ggsav(file, height = input$immune_obja1oup1.h, width = input$immune_obja1oup1.w, 
            plot = immune_obja1oup1() + theme(legend.position = "none") + 
              scale_x_continuous(limits = immune_obja1oup1xy$x, expand = c(0, 0)) + 
              scale_y_continuous(limits = immune_obja1oup1xy$y, expand = c(0, 0)))
    }
})
output$immune_obja1oup3 <- renderPlot({grid.newpage(); grid.draw(g_legend(immune_obja1oup1()))})
output$immune_obja1oup3.ui <- renderUI({plotOutput("immune_obja1oup3", height = 72*convertHeight(
  grobHeight(g_legend(immune_obja1oup1())), unitTo="in", valueOnly=TRUE) + 50)})
output$immune_obja1oup3.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja1dr,"_",input$immune_obja1inp1,"_leg.",input$immune_obja1oup3.f) },
  content = function(file) { 
    grid.newpage(); grid.draw(g_legend(immune_obja1oup1()))
    ggsav(file, height = input$immune_obja1oup3.h, width = input$immune_obja1oup3.w, plot = grid.grab())
}) 

output$immune_obja1.dt <- renderDataTable({
  ggData = sc2Dnum(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja1dr, immune_obja1oup1xy$x, immune_obja1oup1xy$y, input$immune_obja1inp1,
                   immune_h5, immune_objgene, input$immune_obja1ass1, input$immune_obja1sub1, input$immune_obja1sub2, input$immune_obja1splt)
  datatable(ggData, rownames = FALSE, extensions = "Buttons",
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>%
    formatRound(columns = c("pctZoom"), digits = 2)
})


### Functions for tab A2 
getGimmune_obja2inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$immune_obja2ass1)) 
  if(gsub("^Assay: ", "", input$immune_obja2ass1) == "Cell Information"){ 
    res <- immune_objconf$UI 
    resDef <- immune_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(immune_objgene[[gsub("^Assay: ", "", input$immune_obja2ass1)]]) 
    resDef <- immune_objdef$gene1[[gsub("^Assay: ", "", input$immune_obja2ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$immune_obja2ass1), {
  updateSelectizeInput(session, "immune_obja2inp1", choices = getGimmune_obja2inp1()[[1]], 
                       server = TRUE, selected = getGimmune_obja2inp1()[[2]], options = list( 
                         maxOptions = getGimmune_obja2inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
getGimmune_obja2inp2 <- reactive({ 
  req(gsub("^Assay: ", "", input$immune_obja2ass2)) 
  if(gsub("^Assay: ", "", input$immune_obja2ass2) == "Cell Information"){ 
    res <- immune_objconf$UI 
    resDef <- immune_objdef$meta1 
    resLen <- length(res) 
  } else { 
    res <- names(immune_objgene[[gsub("^Assay: ", "", input$immune_obja2ass2)]]) 
    resDef <- immune_objdef$gene1[[gsub("^Assay: ", "", input$immune_obja2ass2)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$immune_obja2ass2), {
  updateSelectizeInput(session, "immune_obja2inp2", choices = getGimmune_obja2inp2()[[1]], 
                       server = TRUE, selected = getGimmune_obja2inp2()[[2]], options = list( 
                         maxOptions = getGimmune_obja2inp2()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
  output$immune_obja2sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_obja2sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_obja2sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_obja2sub1non, {
  sub = strsplit(immune_objconf[UI == input$immune_obja2sub1]$fID, "\\|")[[1]]
  updateCheckboxGroupInput(session, inputId = "immune_obja2sub2", label = "Select which cells to show",
                           choices = sub, selected = NULL, inline = TRUE)
})
observeEvent(input$immune_obja2sub1all, {
  sub = strsplit(immune_objconf[UI == input$immune_obja2sub1]$fID, "\\|")[[1]]
  updateCheckboxGroupInput(session, inputId = "immune_obja2sub2", label = "Select which cells to show",
                           choices = sub, selected = sub, inline = TRUE)
})

immune_obja2oup1 <- reactive({
  sc2Ddimr(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja2dr, input$immune_obja2inp1,
           immune_h5, immune_objgene, input$immune_obja2ass1, input$immune_obja2sub1, input$immune_obja2sub2,  
           input$immune_obja2min1, input$immune_obja2max1, input$immune_obja2siz, input$immune_obja2ord1,
           cList[[input$immune_obja2col1]], sList[input$immune_obja2fsz], 
           input$immune_obja2asp, input$immune_obja2txt, input$immune_obja2lab1) 
})
output$immune_obja2oup1 <- renderPlot({immune_obja2oup1() + theme(legend.position = "none")})
output$immune_obja2oup1.ui <- renderUI({plotOutput("immune_obja2oup1", height = pList[input$immune_obja2psz])})
output$immune_obja2oup1.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja2dr,"_",input$immune_obja2inp1,".",input$immune_obja2oup1.f) },
  content = function(file) { ggsav(file, height = input$immune_obja2oup1.h, width = input$immune_obja2oup1.w, 
                                   plot = immune_obja2oup1() + theme(legend.position = "none"))
})
output$immune_obja2oup3 <- renderPlot({grid.newpage(); grid.draw(g_legend(immune_obja2oup1()))})
output$immune_obja2oup3.ui <- renderUI({plotOutput("immune_obja2oup3", height = 72*convertHeight(
  grobHeight(g_legend(immune_obja2oup1())), unitTo="in", valueOnly=TRUE) + 50)})
output$immune_obja2oup3.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja2dr,"_",input$immune_obja2inp1,"_leg.",input$immune_obja2oup3.f) },
content = function(file) { 
  grid.newpage(); grid.draw(g_legend(immune_obja2oup1()))
  ggsav(file, height = input$immune_obja2oup3.h, width = input$immune_obja2oup3.w, plot = grid.grab())
})

immune_obja2oup2 <- reactive({
  sc2Ddimr(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja2dr, input$immune_obja2inp2,
           immune_h5, immune_objgene, input$immune_obja2ass2, input$immune_obja2sub1, input$immune_obja2sub2,  
           input$immune_obja2min2, input$immune_obja2max2, input$immune_obja2siz, input$immune_obja2ord2,
           cList[[input$immune_obja2col2]], sList[input$immune_obja2fsz], 
           input$immune_obja2asp, input$immune_obja2txt, input$immune_obja2lab2) 
})
output$immune_obja2oup2 <- renderPlot({immune_obja2oup2() + theme(legend.position = "none")})
output$immune_obja2oup2.ui <- renderUI({plotOutput("immune_obja2oup2", height = pList[input$immune_obja2psz])})
output$immune_obja2oup2.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja2dr,"_",input$immune_obja2inp2,".",input$immune_obja2oup2.f) },
  content = function(file) { ggsav(file, height = input$immune_obja2oup2.h, width = input$immune_obja2oup2.w, 
                                   plot = immune_obja2oup2() + theme(legend.position = "none"))
})

output$immune_obja2oup4 <- renderPlot({grid.newpage(); grid.draw(g_legend(immune_obja2oup2()))})
output$immune_obja2oup4.ui <- renderUI({plotOutput("immune_obja2oup4", height = 72*convertHeight(
  grobHeight(g_legend(immune_obja2oup2())), unitTo="in", valueOnly=TRUE) + 50)})
output$immune_obja2oup4.dl <- downloadHandler(
  filename = function() { paste0("immune_obj",input$immune_obja2dr,"_",input$immune_obja2inp2,"_leg.",input$immune_obja2oup4.f) },
content = function(file) { 
  grid.newpage(); grid.draw(g_legend(immune_obja2oup2()))
  ggsav(file, height = input$immune_obja2oup4.h, width = input$immune_obja2oup4.w, plot = grid.grab())
})

immune_obja2oup5 <- reactive({
  sc2Dcomp(immune_objconf, immune_objmeta, input$immune_obja2inp1, input$immune_obja2inp2,
           immune_h5, immune_objgene, input$immune_obja2ass1, input$immune_obja2ass2, input$immune_obja2sub1, input$immune_obja2sub2,
           input$immune_obja2min1, input$immune_obja2max1, input$immune_obja2min2, input$immune_obja2max2, 
           input$immune_obja2siz, cList[[input$immune_obja2col2]], sList[input$immune_obja2fsz]) 
})
output$immune_obja2oup5 <- renderPlot({immune_obja2oup5() + theme(legend.position = "none")})
output$immune_obja2oup5.ui <- renderUI({plotOutput("immune_obja2oup5", height = pList[input$immune_obja2psz])})
output$immune_obja2oup5.dl <- downloadHandler( 
  filename = function() { paste0("immune_objcompare_",input$immune_obja2inp1,"_",input$immune_obja2inp2,".",input$immune_obja2oup5.f) }, 
  content = function(file) { ggsav(file, height = input$immune_obja2oup5.h, width = input$immune_obja2oup5.w, 
                                   plot = immune_obja2oup5()) 
}) 
output$immune_obja2.dt <- renderDataTable({
  ggData = sc2Dcnum(immune_objconf, immune_objmeta, input$immune_obja2inp1, input$immune_obja2inp2,
                    immune_h5, immune_objgene, input$immune_obja2ass1, input$immune_obja2ass2, input$immune_obja2sub1, input$immune_obja2sub2,
                    input$immune_obja2min1, input$immune_obja2max1, input$immune_obja2min2, input$immune_obja2max2, input$immune_obja2cut)
  datatable(ggData, rownames = FALSE, extensions = "Buttons",
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel")))
})


### Functions for tab A3 
getGimmune_obja3inp1 <- reactive({ 
  req(input$immune_obja3ass1) 
  res <- names(immune_objgene[[input$immune_obja3ass1]]) 
  resDef1 <- immune_objdef$gene1[[input$immune_obja3ass1]] 
  resDef2 <- immune_objdef$gene2[[input$immune_obja3ass1]] 
  return(list(res,resDef1,resDef2))
})
observeEvent(input$immune_obja3ass1, {
  updateSelectizeInput(session, "immune_obja3inp1", choices = getGimmune_obja3inp1()[[1]], 
                       server = TRUE, selected = getGimmune_obja3inp1()[[2]], options = list( 
                         maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) 
})
observeEvent(input$immune_obja3ass1, {
  updateSelectizeInput(session, "immune_obja3inp2", choices = getGimmune_obja3inp1()[[1]], 
                       server = TRUE, selected = getGimmune_obja3inp1()[[3]], options = list( 
                         maxOptions = 7, create = TRUE, persist = TRUE, render = I(optCrt))) 
})
output$immune_obja3sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_obja3sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_obja3sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_obja3sub1non, { 
  sub = strsplit(immune_objconf[UI == input$immune_obja3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_obja3sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$immune_obja3sub1all, { 
  sub = strsplit(immune_objconf[UI == input$immune_obja3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_obja3sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 
immune_obja3oup1 <- reactive({
  scDRcoex(immune_objconf, immune_objmeta, immune_objdimr, input$immune_obja3dr, input$immune_obja3inp1, input$immune_obja3inp2, 
           paste0(immune_h5, input$immune_obja3ass1, ".h5"), immune_objgene[[input$immune_obja3ass1]], 
           input$immune_obja3sub1, input$immune_obja3sub2, input$immune_obja3min1, input$immune_obja3max1, input$immune_obja3min2, input$immune_obja3max2, 
           input$immune_obja3siz, input$immune_obja3col1, input$immune_obja3ord1, 
           sList[input$immune_obja3fsz], input$immune_obja3asp, input$immune_obja3txt) 
}) 
output$immune_obja3oup1 <- renderPlot({immune_obja3oup1()}) 
output$immune_obja3oup1.ui <- renderUI({plotOutput("immune_obja3oup1", height = pList2[input$immune_obja3psz])}) 
output$immune_obja3oup1.dl <- downloadHandler( 
  filename = function() { paste0("immune_obj",input$immune_obja3dr,"_",input$immune_obja3inp1,"_",input$immune_obja3inp2,".",input$immune_obja3oup1.f) }, 
  content = function(file) { ggsav(file, height = input$immune_obja3oup1.h, width = input$immune_obja3oup1.w, plot = immune_obja3oup1())
}) 

output$immune_obja3oup2 <- renderPlot({scDRcoexLeg(input$immune_obja3inp1, input$immune_obja3inp2, input$immune_obja3col1, sList[input$immune_obja3fsz])}) 
output$immune_obja3oup2.ui <- renderUI({plotOutput("immune_obja3oup2", height = "300px")})
output$immune_obja3oup2.dl <- downloadHandler( 
  filename = function() { paste0("immune_obj",input$immune_obja3dr,"_",input$immune_obja3inp1,"_",input$immune_obja3inp2,"_leg.",input$immune_obja3oup2.f) }, 
  content = function(file) { ggsav(file, height = 3, width = 4, 
                                   plot = scDRcoexLeg(input$immune_obja3inp1, input$immune_obja3inp2, input$immune_obja3col1, sList[input$immune_obja3fsz]))
}) 
output$immune_obja3.dt <- renderDataTable({ 
  ggData = scDRcoexNum(immune_objconf, immune_objmeta, input$immune_obja3inp1, input$immune_obja3inp2, 
                       paste0(immune_h5, input$immune_obja3ass1, ".h5"), immune_objgene[[input$immune_obja3ass1]], 
                       input$immune_obja3sub1, input$immune_obja3sub2) 
  datatable(ggData, rownames = FALSE, extensions = "Buttons", 
            options = list(pageLength = -1, dom = "tB", buttons = c("copy", "csv", "excel"))) %>% 
    formatRound(columns = c("percent"), digits = 2) 
}) 


### Functions for tab B1 
getGimmune_objb1inp1 <- reactive({ 
  req(gsub("^Assay: ", "", input$immune_objb1ass1)) 
  if(gsub("^Assay: ", "", input$immune_objb1ass1) == "Cell Information"){ 
    res <- immune_objconf[is.na(fID)]$UI 
    resDef <- immune_objconf[is.na(fID)]$UI[1] 
    resLen <- length(res) 
  } else { 
    res <- names(immune_objgene[[gsub("^Assay: ", "", input$immune_objb1ass1)]]) 
    resDef <- immune_objdef$gene1[[gsub("^Assay: ", "", input$immune_objb1ass1)]] 
    resLen <- 7 
  } 
  return(list(res,resDef,resLen))
})
observeEvent(gsub("^Assay: ", "", input$immune_objb1ass1), {
  updateSelectizeInput(session, "immune_objb1inp2", choices = getGimmune_objb1inp1()[[1]], 
                       server = TRUE, selected = getGimmune_objb1inp1()[[2]], options = list( 
                         maxOptions = getGimmune_objb1inp1()[[3]], create = TRUE, 
                         persist = TRUE, render = I(optCrt))) 
})
output$immune_objb1sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_objb1sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_objb1sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_objb1sub1non, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb1sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$immune_objb1sub1all, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb1sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb1sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

immune_objb1oup <- reactive({
  scVioBox(immune_objconf, immune_objmeta, input$immune_objb1inp1, input$immune_objb1inp2, 
           immune_h5, immune_objgene, input$immune_objb1ass1, 
           input$immune_objb1sub1, input$immune_objb1sub2, input$immune_objb1typ, input$immune_objb1pts, 
           input$immune_objb1stg, input$immune_objb1stp1, input$immune_objb1stp2, 
           input$immune_objb1siz, sList[input$immune_objb1fsz], input$immune_objb1noi) 
}) 
output$immune_objb1oup <- renderPlot({immune_objb1oup()}) 
output$immune_objb1oup.ui <- renderUI({plotOutput("immune_objb1oup", height = pList2[input$immune_objb1psz])}) 
output$immune_objb1oup.dl <- downloadHandler( 
  filename = function() { paste0("immune_obj",input$immune_objb1typ,"_",input$immune_objb1inp1,"_",input$immune_objb1inp2,".",input$immune_objb1oup.f) }, 
  content = function(file) { ggsave(file, height = input$immune_objb1oup.h, width = input$immune_objb1oup.w, plot = immune_objb1oup())
}) 


### Functions for tab B2 
observeEvent(input$immune_objb2inp1, {
  sub = strsplit(immune_objconf[UI == input$immune_objb2inp2]$fID, "\\|")[[1]] 
  updateSelectizeInput(session, "immune_objb2ord1", choices = c("Original order", sub), 
                       server = TRUE, selected = "Original order", options = list( 
                       create = TRUE, persist = TRUE, render = I(optCrt))) 
}) 
output$immune_objb2sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_objb2sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_objb2sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_objb2sub1non, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb2sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb2sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$immune_objb2sub1all, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb2sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb2sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 

immune_objb2oup  <- reactive({
  scProp(immune_objconf, immune_objmeta, input$immune_objb2inp1, input$immune_objb2inp2,  
         input$immune_objb2sub1, input$immune_objb2sub2, input$immune_objb2ord1, input$immune_objb2ord2, 
         input$immune_objb2typ, input$immune_objb2flp, sList[input$immune_objb2fsz]) 
})
output$immune_objb2oup <- renderPlot({immune_objb2oup()}) 
output$immune_objb2oup.ui <- renderUI({plotOutput("immune_objb2oup", height = pList2[input$immune_objb2psz])}) 
output$immune_objb2oup.dl <- downloadHandler( 
  filename = function() { paste0("immune_obj",input$immune_objb2typ,"_",input$immune_objb2inp1,"_",input$immune_objb2inp2,".",input$immune_objb2oup.f) }, 
  content = function(file) { ggsave(file, height = input$immune_objb2oup.h, width = input$immune_objb2oup.w, plot = immune_objb2oup())
}) 


### Functions for tab B3 
getGimmune_objb3inp1 <- reactive({ 
  req(input$immune_objb3ass1) 
  resDef <- paste0(immune_objdef$genes[[input$immune_objb3ass1]], 
                   collapse = ", ") 
  return(resDef) 
}) 
observeEvent(input$immune_objb3ass1, { 
  updateTextAreaInput(session, "immune_objb3inp", value = getGimmune_objb3inp1()) 
}) 
output$immune_objb3sub1.ui <- renderUI({ 
  sub = strsplit(immune_objconf[UI == input$immune_objb3sub1]$fID, "\\|")[[1]] 
  checkboxGroupInput("immune_objb3sub2", "Select which cells to show", inline = TRUE, 
                     choices = sub, selected = sub) 
}) 
observeEvent(input$immune_objb3sub1non, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb3sub2", label = "Select which cells to show", 
                           choices = sub, selected = NULL, inline = TRUE) 
}) 
observeEvent(input$immune_objb3sub1all, { 
  sub = strsplit(immune_objconf[UI == input$immune_objb3sub1]$fID, "\\|")[[1]] 
  updateCheckboxGroupInput(session, inputId = "immune_objb3sub2", label = "Select which cells to show", 
                           choices = sub, selected = sub, inline = TRUE) 
}) 
output$immune_objb3oupTxt <- renderUI({ 
  geneList = scGeneList(input$immune_objb3inp, immune_objgene[[input$immune_objb3ass1]]) 
  if(nrow(geneList) > 50){ 
    HTML("More than 50 input genes! Please reduce the gene list!") 
  } else { 
    oup = paste0(nrow(geneList[present == TRUE]), " genes OK and will be plotted") 
    if(nrow(geneList[present == FALSE]) > 0){ 
      oup = paste0(oup, "<br/>", 
                   nrow(geneList[present == FALSE]), " genes not found (", 
                   paste0(geneList[present == FALSE]$gene, collapse = ", "), ")") 
    } 
    HTML(oup) 
  } 
}) 

#########################################################################
# Manual Edit 02 - Immune subset
# Cell Type Mode addition to heatmap/bubblepot. 
# Allows users to plot gene expression across batch/sample_id/timepoint
# for one selected celltype. 
#########################################################################

immune_objb3oup <- reactive({
  # this section was added to support switched between the default subsetting and the cell type mode
  if (input$immune_objb3_use_celltype) {
    sub1 <- "annotated_celltype"                  # subset by cell type annotation
    sub2 <- c(input$immune_objb3_celltype)        # selected cell type
    grp  <- input$immune_objb3_celltype_grp       # group by chosen variable
    scl  <- input$immune_objb3scl                 # apply scaling if selected
  # otherwise do default subsetting
  } else {
    sub1 <- input$immune_objb3sub1
    sub2 <- input$immune_objb3sub2
    grp  <- input$immune_objb3grp
    scl  <- input$immune_objb3scl
  }

  # this section was added to catch and rename the error in cell type mode when not enough cell information is present
  # this prompts the user to try and remove the gene expression scaling
  tryCatch({

  scBubbHeat(immune_objconf, immune_objmeta, input$immune_objb3inp,
             grp, input$immune_objb3plt,
             paste0(immune_h5, input$immune_objb3ass1, ".h5"),
             immune_objgene[[input$immune_objb3ass1]],
             sub1, sub2, scl,
             input$immune_objb3row, input$immune_objb3col,
             cList[[input$immune_objb3cols]], sList[input$immune_objb3fsz],
             input$immune_objb3exp, input$immune_objb3max)
  # error catching as described above
  }, error = function(e) {
    if (grepl("NA/NaN/Inf", e$message)) {
      stop("Not enough cell information — try removing scaled expression or check for low-variance genes.")
    } else {
      stop(e)
    }
  })
}) 
  
  
#########################################################################
#########################################################################
  
output$immune_objb3oup <- renderPlot({immune_objb3oup()}) 
output$immune_objb3oup.ui <- renderUI({plotOutput("immune_objb3oup", height = pList3[input$immune_objb3psz])})
output$immune_objb3oup.dl <- downloadHandler( 
  filename = function() { paste0("immune_obj",input$immune_objb3plt,"_",input$immune_objb3grp,".",input$immune_objb3oup.f) }, 
  content = function(file) { ggsave(file, height = input$immune_objb3oup.h, width = input$immune_objb3oup.w, plot = immune_objb3oup())
}) 


}) 


