library(shiny) 
library(shinyhelper) 
library(data.table) 
library(Matrix) 
library(DT) 
library(magrittr) 

#### auto-detect environment (this was updated by Emma Bolech after the script was generated by "makeShinyAppV4.R") ####
data_path <- if (file.exists("./merged_objconf.rds")) {
  "./"
} else if (file.exists("/srv/shiny-server/data/merged_objconf.rds")) {
  "/srv/shiny-server/data/"
} else {
  stop("Data not found in either local or mounted path")
}

# replace auto-created file paths with the below block
#### the file paths here were updated by Emma Bolech after the script was generated ####
merged_objconf = readRDS(paste0(data_path,"merged_objconf.rds"))
merged_objdef  = readRDS(paste0(data_path,"merged_objdef.rds"))
immune_objconf = readRDS(paste0(data_path,"immune_objconf.rds"))
immune_objdef  = readRDS(paste0(data_path,"immune_objdef.rds"))


### Start server code 
shinyUI(fluidPage( 
  ### HTML formatting of error messages 
   
  tags$head(tags$style(HTML(".shiny-output-error-validation {color: red; font-weight: bold;}"))), 
  list(tags$style(HTML(".navbar-default .navbar-nav { font-weight: bold; font-size: 16px; }"))), 
  
  ### Page title 
  titlePanel("Single-Cell RNA-seq Time Course of Axolotl Limb Regeneration"), 
  navbarPage( 
    NULL, 
navbarMenu("All Cells",### Tab1.a1: Zoom-enable Dimred 
tabPanel( 
  HTML("Zoom-enable Dimred"), 
  h4("Zoom-enable reduced dimensions overlaid with cell info or assay expression"), 
  "In this tab, users can visualise either cell information and gene expression ",  
  "in a zoom-enabled low-dimensional representions plots.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow( 
        column( 
          12, selectInput("merged_obja1dr", "Reduction:", choices = merged_objdef$dimrd, 
                          selected = merged_objdef$dimrd[1])) 
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("merged_obja1togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_obja1togL % 2 == 1", 
        selectInput("merged_obja1sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_obja1sub1.ui"), 
        actionButton("merged_obja1sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_obja1sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("merged_obja1tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_obja1tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("merged_obja1siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("merged_obja1psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("merged_obja1fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("merged_obja1asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("merged_obja1txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", h4("Information to plot"),
      selectInput("merged_obja1ass1", "Data type to colour plot:",
                  choices = c("Cell Information", paste0("Assay: ", merged_objdef$assay)), 
                  selected = "Cell Information"), 
      selectInput("merged_obja1inp1", "Cell Info / Feature Name:", choices = NULL) %>% 
        helper(type = "inline", size = "m", fade = TRUE,
               title = "Cell Info / Gene to colour cells by",
               content = c("Select cell info / feature to colour cells",
                           "- Categorical covariates have a fixed colour palette",
                           paste0("- Continuous covariates / gene expression are coloured ",
                                  "in a Blue-Yellow-Red colour scheme, which can be ",
                                  "changed in the plot controls"))),
      strong("Draw box on plot below to zoom: "), 
      plotOutput("merged_obja1oup1.br", height = "400px",
                 brush = brushOpts(id = "merged_obja1inp1.br", resetOnNew = TRUE)), 
      actionButton("merged_obja1tog1", "Toggle plot controls"), 
      conditionalPanel(
        condition = "input.merged_obja1tog1 % 2 == 1",
        radioButtons("merged_obja1col1", "Colour (Continuous data):",
                     choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                     selected = "Blue-Yellow-Red"),
        numericInput("merged_obja1min1", "Min cutoff (q##):",
                     min = 0, max = 50, value = 0, step = 1),
        numericInput("merged_obja1max1", "Max cutoff (q##):",
                     min = 50, max = 100, value = 100, step = 1),
        radioButtons("merged_obja1ord1", "Plot order:",
                     choices = c("Max-1st", "Min-1st", "Original", "Random"),
                     selected = "Original", inline = TRUE),
        checkboxInput("merged_obja1lab1", "Show cell info labels", value = TRUE)
      )
    ), # End of column (6 space) 
    column( 
      6, style="border-right: 2px solid black", 
      fluidRow(column(12, uiOutput("merged_obja1oup1.ui"))),
      fluidRow(column(12, uiOutput("merged_obja1oup3.ui"))),
      fluidRow(column(3, downloadButton("merged_obja1oup1.dl", "Download Plot")),
               column(3, radioButtons("merged_obja1oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja1oup1.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("merged_obja1oup1.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("merged_obja1oup3.dl", "Download Legend")),
               column(3, radioButtons("merged_obja1oup3.f", "Legend format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja1oup3.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("merged_obja1oup3.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br() 
    ), # End of column (6 space) 
    column(
      3, h4("Cell numbers"), 
      numericInput("merged_obja1splt", "Split continuous cell info into nBins:",
                   min = 2, max = 10, value = 4, step = 1),
      dataTableOutput("merged_obja1.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.a2: CellInfo vs AssayExpr on dimRed 
tabPanel( 
  HTML("Side-by-side DimRed"), 
  h4("Cell information vs assay expression on reduced dimensions"), 
  "In this tab, users can visualise both cell information and gene ",  
  "expression side-by-side on low-dimensional representions.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow(
        column(
          12, selectInput("merged_obja2dr", "Reduction:", choices = merged_objdef$dimrd, 
                          selected = merged_objdef$dimrd[1]))
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("merged_obja2togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_obja2togL % 2 == 1", 
        selectInput("merged_obja2sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_obja2sub1.ui"), 
        actionButton("merged_obja2sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_obja2sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("merged_obja2tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_obja2tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("merged_obja2siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("merged_obja2psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("merged_obja2fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("merged_obja2asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("merged_obja2txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column(
      6, style="border-right: 2px solid black",
      fluidRow(
        column(
          6, selectInput("merged_obja2ass1", "Data type to colour plot:",
                         choices = c("Cell Information", paste0("Assay: ", merged_objdef$assay)), 
                         selected = "Cell Information"), 
          selectInput("merged_obja2inp1", "Cell Info / Feature Name:", choices = NULL) %>% 
            helper(type = "inline", size = "m", fade = TRUE,
                   title = "Cell Info / Gene to colour cells by",
                   content = c("Select cell info / feature to colour cells",
                               "- Categorical covariates have a fixed colour palette",
                               paste0("- Continuous covariates / gene expression are coloured ",
                                      "in a Blue-Yellow-Red colour scheme, which can be ",
                                      "changed in the plot controls")))
        ),
        column(
          6, actionButton("merged_obja2tog1", "Toggle plot controls"),
          conditionalPanel(
            condition = "input.merged_obja2tog1 % 2 == 1",
            radioButtons("merged_obja2col1", "Colour (Continuous data):",
                         choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                         selected = "Blue-Yellow-Red"),
            numericInput("merged_obja2min1", "Min cutoff (q##):",
                         min = 0, max = 50, value = 0, step = 1),
            numericInput("merged_obja2max1", "Max cutoff (q##):",
                         min = 50, max = 100, value = 100, step = 1),
            radioButtons("merged_obja2ord1", "Plot order:",
                         choices = c("Max-1st", "Min-1st", "Original", "Random"),
                         selected = "Original", inline = TRUE),
            checkboxInput("merged_obja2lab1", "Show cell info labels", value = TRUE)
          )
        )
      ),
      fluidRow(column(12, uiOutput("merged_obja2oup1.ui"))),
      fluidRow(column(12, uiOutput("merged_obja2oup3.ui"))),
      fluidRow(column(3, downloadButton("merged_obja2oup1.dl", "Download Plot")),
               column(3, radioButtons("merged_obja2oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja2oup1.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("merged_obja2oup1.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("merged_obja2oup3.dl", "Download Legend")),
              column(3, radioButtons("merged_obja2oup3.f", "Legend format:", 
                                     choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja2oup3.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("merged_obja2oup3.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br() 
    ), # End of column (6 space)
    column( 
      6,
      fluidRow( 
        column(
          6, selectInput("merged_obja2ass2", "Data type to colour plot:",
                         choices = c("Cell Information", paste0("Assay: ", merged_objdef$assay)), 
                         selected = paste0("Assay: ", merged_objdef$assay[1])), 
          selectInput("merged_obja2inp2", "Cell Info / Feature Name:", choices = NULL) %>% 
            helper(type = "inline", size = "m", fade = TRUE,
                   title = "Cell Info / Gene to colour cells by",
                   content = c("Select cell info / feature to colour cells",
                               "- Categorical covariates have a fixed colour palette",
                               paste0("- Continuous covariates / gene expression are coloured ",
                                      "in a Blue-Yellow-Red colour scheme, which can be ",
                                      "changed in the plot controls")))
        ),
        column(
          6, actionButton("merged_obja2tog2", "Toggle plot controls"),
          conditionalPanel(
            condition = "input.merged_obja2tog2 % 2 == 1",
            radioButtons("merged_obja2col2", "Colour (Continuous data):",
                         choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                         selected = "White-Red"),
            numericInput("merged_obja2min2", "Min cutoff (q##):",
                         min = 0, max = 50, value = 0, step = 1),
            numericInput("merged_obja2max2", "Max cutoff (q##):",
                         min = 50, max = 100, value = 100, step = 1),
            radioButtons("merged_obja2ord2", "Plot order:",
                         choices = c("Max-1st", "Min-1st", "Original", "Random"),
                         selected = "Max-1st", inline = TRUE),
            checkboxInput("merged_obja2lab2", "Show cell info labels", value = TRUE)
          )
        )
      ) , 
      fluidRow(column(12, uiOutput("merged_obja2oup2.ui"))),
      fluidRow(column(12, uiOutput("merged_obja2oup4.ui"))),
      fluidRow(column(3, downloadButton("merged_obja2oup2.dl", "Download Plot")),
               column(3, radioButtons("merged_obja2oup2.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja2oup2.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("merged_obja2oup2.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("merged_obja2oup4.dl", "Download Legend")),
               column(3, radioButtons("merged_obja2oup4.f", "Legend format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja2oup4.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("merged_obja2oup4.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br()
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  h4("Relationship between left-side and right-side cell info / feature"),
  fluidRow(
    column(
      6, h4("Comparative plot"), 
      style="border-right: 2px solid black", 
      uiOutput("merged_obja2oup5.ui"), 
      fluidRow(column(3, downloadButton("merged_obja2oup5.dl", "Download Plot")),
               column(3, radioButtons("merged_obja2oup5.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("merged_obja2oup5.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("merged_obja2oup5.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5)))
    ),
    column(
      6, h4("Cell numbers / statistics"), 
      numericInput("merged_obja2cut", "Cutoff for Expression:", value = 0), 
      dataTableOutput("merged_obja2.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.a3: Gene coexpression plot 
tabPanel( 
  HTML("Gene coexpression"), 
  h4("Coexpression of two genes on reduced dimensions"), 
  "In this tab, users can visualise the coexpression of two genes ", 
  "on low-dimensional representions.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow( 
        column( 
          12, selectInput("merged_obja3dr", "Reduction:", choices = merged_objdef$dimrd, 
                          selected = merged_objdef$dimrd[1])) 
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("merged_obja3togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_obja3togL % 2 == 1", 
        selectInput("merged_obja3sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_obja3sub1.ui"), 
        actionButton("merged_obja3sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_obja3sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("merged_obja3tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_obja3tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("merged_obja3siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("merged_obja3psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("merged_obja3fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("merged_obja3asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("merged_obja3txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", h4("Assay Expression"), 
      selectInput("merged_obja3inp1", "Feature 1:", choices=NULL) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
              title = "Feature expression to colour cells by", 
              content = c("Select gene to colour cells by gene expression", 
                         paste0("- Feature expression are coloured in a ", 
                                "White-Red colour scheme which can be ", 
                                "changed in the plot controls"))), 
      selectInput("merged_obja3inp2", "Feature 2:", choices=NULL) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Feature expression to colour cells by", 
               content = c("Select gene to colour cells by gene expression", 
                           paste0("- Feature expression are coloured in a ", 
                                  "White-Blue colour scheme which can be ", 
                                  "changed in the plot controls"))), 
      selectInput("merged_obja3ass1", "Assay:", 
                  choices = merged_objdef$assay, 
                  selected = merged_objdef$assay[1]), 
      actionButton("merged_obja3tog1", "Toggle plot controls"), 
      conditionalPanel( 
        condition = "input.merged_obja3tog1 % 2 == 1", 
        radioButtons("merged_obja3col1", "Colour:", 
                     choices = c("Red (Gene1); Blue (Gene2)", 
                                 "Orange (Gene1); Blue (Gene2)", 
                                 "Red (Gene1); Green (Gene2)", 
                                 "Green (Gene1); Blue (Gene2)"), 
                     selected = "Red (Gene1); Blue (Gene2)"), 
        numericInput("merged_obja3min1", "Min cutoff gene 1 (q##):", 
                     min = 0, max = 50, value = 0, step = 1), 
        numericInput("merged_obja3max1", "Max cutoff gene 1 (q##):", 
                     min = 50, max = 100, value = 100, step = 1), 
        numericInput("merged_obja3min2", "Min cutoff gene 2 (q##):", 
                     min = 0, max = 50, value = 0, step = 1), 
        numericInput("merged_obja3max2", "Max cutoff gene 2 (q##):", 
                     min = 50, max = 100, value = 100, step = 1), 
        radioButtons("merged_obja3ord1", "Plot order:", 
                     choices = c("Max-1st", "Min-1st", "Original", "Random"), 
                     selected = "Max-1st", inline = TRUE) 
      ) 
    ), # End of column (6 space) 
    column( 
      6, style="border-right: 2px solid black", 
      uiOutput("merged_obja3oup1.ui"), 
      fluidRow(column(3, downloadButton("merged_obja3oup1.dl", "Download Plot")), 
               column(3, radioButtons("merged_obja3oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
               column(3, numericInput("merged_obja3oup1.h", "Plot height:", 
                                      min = 4, max = 20, value = 8, step = 0.5)), 
               column(3, numericInput("merged_obja3oup1.w", "Plot width:", 
                                      min = 4, max = 20, value = 8, step = 0.5))), 
      br() 
    ), # End of column (6 space) 
    column( 
      3, uiOutput("merged_obja3oup2.ui"), 
      fluidRow(column(6, downloadButton("merged_obja3oup2.dl", "Download Legend")), 
               column(6, radioButtons("merged_obja3oup2.f", "Legend format:", 
                      choices = c("png", "pdf"), selected = "png", inline = TRUE))), 
      br(), h4("Cell numbers"), 
      dataTableOutput("merged_obja3.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b1: violinplot / boxplot 
tabPanel( 
  HTML("Violinplot / Boxplot"),  
  h4("Cell information / assay expression violin plot / box plot"), 
  "In this tab, users can visualise the assay expression or continuous cell information ",  
  "(e.g. Number of UMIs / module score) across groups of cells (e.g. libary / clusters).", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("merged_objb1inp1", "Cell information (X-axis):", 
                  choices = merged_objconf[grp == TRUE]$UI, 
                  selected = merged_objdef$grp1) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group cells by",  
               content = c("Select categorical cell information to group cells by",  
                           "- Single cells are grouped by this categorical covariate",  
                           "- Plotted as the X-axis of the violin plot / box plot")),  
      selectInput("merged_objb1inp2", "Cell Info / Feature name (Y-axis):", choices=NULL) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell Info / Gene to plot", 
               content = c("Select cell info / feature to plot on Y-axis", 
                           "- Can be continuous cell information (e.g. nUMIs / scores)", 
                           "- Can also be feature expression")), 
      selectInput("merged_objb1ass1", "Data type for Y-axis:", 
                  choices = c("Cell Information", paste0("Assay: ", merged_objdef$assay)), 
                  selected = "Cell Information"), 
      radioButtons("merged_objb1typ", "Plot type:", 
                   choices = c("violin", "boxplot"), 
                   selected = "violin", inline = TRUE), 
      checkboxInput("merged_objb1pts", "Show data points", value = FALSE), 
      actionButton("merged_objb1togT", "Toggle to perform stats test(s)"), 
      conditionalPanel( 
        condition = "input.merged_objb1togT % 2 == 1",  
        radioButtons("merged_objb1stg", "Perform global test:",  
                     choices = c("none","kruskal.test","anova"),  
                     selected = "none"), 
        radioButtons("merged_objb1stp1", "Perform pairwise test:",  
                     choices = c("none","wilcox.test","t.test"),  
                     selected = "none"), 
        textAreaInput("merged_objb1stp2", HTML("Pairwise comparisons to make <br />  
                                             (Separate each pair by new line and <br />  
                                             within each pair using , or ;):"),  
                      height = "150px", value = "none") 
      ), br(), br(),  
      actionButton("merged_objb1togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_objb1togL % 2 == 1", 
        selectInput("merged_objb1sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_objb1sub1.ui"), 
        actionButton("merged_objb1sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_objb1sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("merged_objb1tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_objb1tog % 2 == 1", 
        sliderInput("merged_objb1siz", "Data point size:",  
                    min = 0, max = 4, value = 1.25, step = 0.25),  
        radioButtons("merged_objb1psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("merged_objb1fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        checkboxInput("merged_objb1noi", "Add noise to assay expr", value = TRUE)) 
    ), # End of column (6 space) 
    column(9, uiOutput("merged_objb1oup.ui"), 
    fluidRow(column(2, downloadButton("merged_objb1oup.dl", "Download Plot")), 
             column(2, radioButtons("merged_objb1oup.f", "Plot format:", 
                                    choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
             column(2, numericInput("merged_objb1oup.h", "Plot height:", 
                                    min = 4, max = 20, value = 8, step = 0.5)), 
             column(2, numericInput("merged_objb1oup.w", "Plot width:", 
                                    min = 4, max = 20, value = 10, step = 0.5))), 
    br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b2: Proportion plot 
tabPanel( 
  HTML("Proportion plot"), 
  h4("Proportion / cell numbers across different cell information"), 
  "In this tab, users can visualise the composition of single cells based on one discrete ", 
  "cell information across another discrete cell information. ",  
  "Usage examples include the library or cellcycle composition across clusters.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("merged_objb2inp1", "Cell information to plot (X-axis):", 
                  choices = merged_objconf[grp == TRUE]$UI, 
                  selected = merged_objdef$grp2) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to plot cells by",  
               content = c("Select categorical cell information to plot cells by", 
                           "- Plotted as the X-axis of the proportion plot")), 
      selectInput("merged_objb2inp2", "Cell information to group / colour by:", 
                  choices = merged_objconf[grp == TRUE]$UI, 
                  selected = merged_objdef$grp1) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group / colour cells by", 
               content = c("Select categorical cell information to group / colour cells by", 
                           "- Proportion / cell numbers are shown in different colours")), 
      radioButtons("merged_objb2typ", "Plot value:", 
                   choices = c("Proportion", "CellNumbers"), 
                   selected = "Proportion", inline = TRUE), 
      checkboxInput("merged_objb2flp", "Flip X/Y", value = FALSE), 
      selectInput("merged_objb2ord1", "Reorder X-axis by which group:", choices=NULL), 
      radioButtons("merged_objb2ord2", "Reorder in which order:", 
                   choices = c("Decreasing", "Increasing"), 
                   selected = "Decreasing", inline = TRUE), 
      actionButton("merged_objb2togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_objb2togL % 2 == 1", 
        selectInput("merged_objb2sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_objb2sub1.ui"), 
        actionButton("merged_objb2sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_objb2sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("merged_objb2tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_objb2tog % 2 == 1", 
        radioButtons("merged_objb2psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("merged_objb2fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE)) 
    ), # End of column (6 space) 
    column(9, uiOutput("merged_objb2oup.ui"), 
           fluidRow(column(2, downloadButton("merged_objb2oup.dl", "Download Plot")), 
                    column(2, radioButtons("merged_objb2oup.f", "Plot format:", 
                                           choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
                    column(2, numericInput("merged_objb2oup.h", "Plot height:", 
                                           min = 4, max = 20, value = 8, step = 0.5)), 
                    column(2, numericInput("merged_objb2oup.w", "Plot width:", 
                                           min = 4, max = 20, value = 10, step = 0.5))), 
           br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b3: Bubbleplot / Heatmap 
tabPanel( 
  HTML("Bubbleplot / Heatmap"), 
  h4("Gene expression bubbleplot / heatmap"), 
  "In this tab, users can visualise the gene expression patterns of ", 
  "multiple genes grouped by categorical cell information (e.g. library / cluster).", br(), 
  "The normalised expression are averaged, log-transformed and then plotted.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      textAreaInput("merged_objb3inp", HTML("List of gene names <br /> 
                                        (Max 50 genes, separated <br /> 
                                         by , or ; or newline):"), 
                    height = "250px", 
                    value = paste0(merged_objdef$genes[[1]], collapse = ", ")) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "List of genes to plot on bubbleplot / heatmap", 
               content = c("Input genes to plot", 
                           "- Maximum 50 genes (due to ploting space limitations)", 
                           "- Genes should be separated by comma, semicolon or newline")), 
      selectInput("merged_objb3ass1", "Assay:", 
                  choices = merged_objdef$assay, 
                  selected = merged_objdef$assay[1]), 
      selectInput("merged_objb3grp", "Group by:", 
                  choices = merged_objconf[grp == TRUE]$UI, 
                  selected = merged_objconf[grp == TRUE]$UI[1]) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group cells by", 
               content = c("Select categorical cell information to group cells by", 
                           "- Single cells are grouped by this categorical covariate", 
                           "- Plotted as the X-axis of the bubbleplot / heatmap")), 
      radioButtons("merged_objb3plt", "Plot type:", 
                   choices = c("Bubbleplot", "Heatmap"), 
                   selected = "Bubbleplot", inline = TRUE), 
      checkboxInput("merged_objb3scl", "Scale gene expression", value = TRUE), 
      checkboxInput("merged_objb3row", "Cluster rows (genes)", value = TRUE), 
      checkboxInput("merged_objb3col", "Cluster columns (samples)", value = FALSE), 
      sliderInput("merged_objb3max", "Scale.max:", min=1, max=11, value=3, step=0.1), 
      checkboxInput("merged_objb3exp", "expm1 before averaging (check for log-transformed data)",  
                    value = TRUE), 
      br(), 
      actionButton("merged_objb3togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.merged_objb3togL % 2 == 1", 
        selectInput("merged_objb3sub1", "Cell information to subset:", 
                    choices = merged_objconf[grp == TRUE]$UI, 
                    selected = merged_objdef$grp1), 
        uiOutput("merged_objb3sub1.ui"), 
        actionButton("merged_objb3sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("merged_objb3sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("merged_objb3tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.merged_objb3tog % 2 == 1", 
        radioButtons("merged_objb3cols", "Colour scheme:", 
                     choices = c("White-Red", "Blue-Yellow-Red", 
                                 "Yellow-Green-Purple"), 
                     selected = "Blue-Yellow-Red"), 
        radioButtons("merged_objb3psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("merged_objb3fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE)) 
    ), # End of column (6 space) 
    column(9, h4(htmlOutput("merged_objb3oupTxt")), 
           uiOutput("merged_objb3oup.ui"), 
           fluidRow(column(2, downloadButton("merged_objb3oup.dl", "Download Plot")), 
                    column(2, radioButtons("merged_objb3oup.f", "Plot format:", 
                                           choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
                    column(2, numericInput("merged_objb3oup.h", "Plot height:", 
                                           min = 4, max = 20, value = 10, step = 0.5)), 
                    column(2, numericInput("merged_objb3oup.w", "Plot width:", 
                                           min = 4, max = 20, value = 10, step = 0.5))), 
           br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
), 

navbarMenu("Immune Cells",### Tab1.a1: Zoom-enable Dimred 
tabPanel( 
  HTML("Zoom-enable Dimred"), 
  h4("Zoom-enable reduced dimensions overlaid with cell info or assay expression"), 
  "In this tab, users can visualise either cell information and gene expression ",  
  "in a zoom-enabled low-dimensional representions plots.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow( 
        column( 
          12, selectInput("immune_obja1dr", "Reduction:", choices = immune_objdef$dimrd, 
                          selected = immune_objdef$dimrd[1])) 
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("immune_obja1togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_obja1togL % 2 == 1", 
        selectInput("immune_obja1sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_obja1sub1.ui"), 
        actionButton("immune_obja1sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_obja1sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("immune_obja1tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_obja1tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("immune_obja1siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("immune_obja1psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("immune_obja1fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("immune_obja1asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("immune_obja1txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", h4("Information to plot"),
      selectInput("immune_obja1ass1", "Data type to colour plot:",
                  choices = c("Cell Information", paste0("Assay: ", immune_objdef$assay)), 
                  selected = "Cell Information"), 
      selectInput("immune_obja1inp1", "Cell Info / Feature Name:", choices = NULL) %>% 
        helper(type = "inline", size = "m", fade = TRUE,
               title = "Cell Info / Gene to colour cells by",
               content = c("Select cell info / feature to colour cells",
                           "- Categorical covariates have a fixed colour palette",
                           paste0("- Continuous covariates / gene expression are coloured ",
                                  "in a Blue-Yellow-Red colour scheme, which can be ",
                                  "changed in the plot controls"))),
      strong("Draw box on plot below to zoom: "), 
      plotOutput("immune_obja1oup1.br", height = "400px",
                 brush = brushOpts(id = "immune_obja1inp1.br", resetOnNew = TRUE)), 
      actionButton("immune_obja1tog1", "Toggle plot controls"), 
      conditionalPanel(
        condition = "input.immune_obja1tog1 % 2 == 1",
        radioButtons("immune_obja1col1", "Colour (Continuous data):",
                     choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                     selected = "Blue-Yellow-Red"),
        numericInput("immune_obja1min1", "Min cutoff (q##):",
                     min = 0, max = 50, value = 0, step = 1),
        numericInput("immune_obja1max1", "Max cutoff (q##):",
                     min = 50, max = 100, value = 100, step = 1),
        radioButtons("immune_obja1ord1", "Plot order:",
                     choices = c("Max-1st", "Min-1st", "Original", "Random"),
                     selected = "Original", inline = TRUE),
        checkboxInput("immune_obja1lab1", "Show cell info labels", value = TRUE)
      )
    ), # End of column (6 space) 
    column( 
      6, style="border-right: 2px solid black", 
      fluidRow(column(12, uiOutput("immune_obja1oup1.ui"))),
      fluidRow(column(12, uiOutput("immune_obja1oup3.ui"))),
      fluidRow(column(3, downloadButton("immune_obja1oup1.dl", "Download Plot")),
               column(3, radioButtons("immune_obja1oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja1oup1.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("immune_obja1oup1.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("immune_obja1oup3.dl", "Download Legend")),
               column(3, radioButtons("immune_obja1oup3.f", "Legend format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja1oup3.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("immune_obja1oup3.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br() 
    ), # End of column (6 space) 
    column(
      3, h4("Cell numbers"), 
      numericInput("immune_obja1splt", "Split continuous cell info into nBins:",
                   min = 2, max = 10, value = 4, step = 1),
      dataTableOutput("immune_obja1.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.a2: CellInfo vs AssayExpr on dimRed 
tabPanel( 
  HTML("Side-by-side DimRed"), 
  h4("Cell information vs assay expression on reduced dimensions"), 
  "In this tab, users can visualise both cell information and gene ",  
  "expression side-by-side on low-dimensional representions.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow(
        column(
          12, selectInput("immune_obja2dr", "Reduction:", choices = immune_objdef$dimrd, 
                          selected = immune_objdef$dimrd[1]))
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("immune_obja2togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_obja2togL % 2 == 1", 
        selectInput("immune_obja2sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_obja2sub1.ui"), 
        actionButton("immune_obja2sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_obja2sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("immune_obja2tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_obja2tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("immune_obja2siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("immune_obja2psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("immune_obja2fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("immune_obja2asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("immune_obja2txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column(
      6, style="border-right: 2px solid black",
      fluidRow(
        column(
          6, selectInput("immune_obja2ass1", "Data type to colour plot:",
                         choices = c("Cell Information", paste0("Assay: ", immune_objdef$assay)), 
                         selected = "Cell Information"), 
          selectInput("immune_obja2inp1", "Cell Info / Feature Name:", choices = NULL) %>% 
            helper(type = "inline", size = "m", fade = TRUE,
                   title = "Cell Info / Gene to colour cells by",
                   content = c("Select cell info / feature to colour cells",
                               "- Categorical covariates have a fixed colour palette",
                               paste0("- Continuous covariates / gene expression are coloured ",
                                      "in a Blue-Yellow-Red colour scheme, which can be ",
                                      "changed in the plot controls")))
        ),
        column(
          6, actionButton("immune_obja2tog1", "Toggle plot controls"),
          conditionalPanel(
            condition = "input.immune_obja2tog1 % 2 == 1",
            radioButtons("immune_obja2col1", "Colour (Continuous data):",
                         choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                         selected = "Blue-Yellow-Red"),
            numericInput("immune_obja2min1", "Min cutoff (q##):",
                         min = 0, max = 50, value = 0, step = 1),
            numericInput("immune_obja2max1", "Max cutoff (q##):",
                         min = 50, max = 100, value = 100, step = 1),
            radioButtons("immune_obja2ord1", "Plot order:",
                         choices = c("Max-1st", "Min-1st", "Original", "Random"),
                         selected = "Original", inline = TRUE),
            checkboxInput("immune_obja2lab1", "Show cell info labels", value = TRUE)
          )
        )
      ),
      fluidRow(column(12, uiOutput("immune_obja2oup1.ui"))),
      fluidRow(column(12, uiOutput("immune_obja2oup3.ui"))),
      fluidRow(column(3, downloadButton("immune_obja2oup1.dl", "Download Plot")),
               column(3, radioButtons("immune_obja2oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja2oup1.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("immune_obja2oup1.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("immune_obja2oup3.dl", "Download Legend")),
              column(3, radioButtons("immune_obja2oup3.f", "Legend format:", 
                                     choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja2oup3.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("immune_obja2oup3.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br() 
    ), # End of column (6 space)
    column( 
      6,
      fluidRow( 
        column(
          6, selectInput("immune_obja2ass2", "Data type to colour plot:",
                         choices = c("Cell Information", paste0("Assay: ", immune_objdef$assay)), 
                         selected = paste0("Assay: ", immune_objdef$assay[1])), 
          selectInput("immune_obja2inp2", "Cell Info / Feature Name:", choices = NULL) %>% 
            helper(type = "inline", size = "m", fade = TRUE,
                   title = "Cell Info / Gene to colour cells by",
                   content = c("Select cell info / feature to colour cells",
                               "- Categorical covariates have a fixed colour palette",
                               paste0("- Continuous covariates / gene expression are coloured ",
                                      "in a Blue-Yellow-Red colour scheme, which can be ",
                                      "changed in the plot controls")))
        ),
        column(
          6, actionButton("immune_obja2tog2", "Toggle plot controls"),
          conditionalPanel(
            condition = "input.immune_obja2tog2 % 2 == 1",
            radioButtons("immune_obja2col2", "Colour (Continuous data):",
                         choices = c("White-Red","Blue-Yellow-Red","Yellow-Green-Purple"),
                         selected = "White-Red"),
            numericInput("immune_obja2min2", "Min cutoff (q##):",
                         min = 0, max = 50, value = 0, step = 1),
            numericInput("immune_obja2max2", "Max cutoff (q##):",
                         min = 50, max = 100, value = 100, step = 1),
            radioButtons("immune_obja2ord2", "Plot order:",
                         choices = c("Max-1st", "Min-1st", "Original", "Random"),
                         selected = "Max-1st", inline = TRUE),
            checkboxInput("immune_obja2lab2", "Show cell info labels", value = TRUE)
          )
        )
      ) , 
      fluidRow(column(12, uiOutput("immune_obja2oup2.ui"))),
      fluidRow(column(12, uiOutput("immune_obja2oup4.ui"))),
      fluidRow(column(3, downloadButton("immune_obja2oup2.dl", "Download Plot")),
               column(3, radioButtons("immune_obja2oup2.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja2oup2.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("immune_obja2oup2.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      fluidRow(column(3, downloadButton("immune_obja2oup4.dl", "Download Legend")),
               column(3, radioButtons("immune_obja2oup4.f", "Legend format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja2oup4.h", "Legend height:",
                                      min = 0.2, max = 10, value = 2, step = 0.1)),
               column(3, numericInput("immune_obja2oup4.w", "Legend width:",
                                      min = 4, max = 20, value = 8, step = 0.5))),
      br()
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  h4("Relationship between left-side and right-side cell info / feature"),
  fluidRow(
    column(
      6, h4("Comparative plot"), 
      style="border-right: 2px solid black", 
      uiOutput("immune_obja2oup5.ui"), 
      fluidRow(column(3, downloadButton("immune_obja2oup5.dl", "Download Plot")),
               column(3, radioButtons("immune_obja2oup5.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)),
               column(3, numericInput("immune_obja2oup5.h", "Plot height:",
                                      min = 4, max = 20, value = 8, step = 0.5)),
               column(3, numericInput("immune_obja2oup5.w", "Plot width:",
                                      min = 4, max = 20, value = 8, step = 0.5)))
    ),
    column(
      6, h4("Cell numbers / statistics"), 
      numericInput("immune_obja2cut", "Cutoff for Expression:", value = 0), 
      dataTableOutput("immune_obja2.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.a3: Gene coexpression plot 
tabPanel( 
  HTML("Gene coexpression"), 
  h4("Coexpression of two genes on reduced dimensions"), 
  "In this tab, users can visualise the coexpression of two genes ", 
  "on low-dimensional representions.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, fluidRow( 
        column( 
          12, selectInput("immune_obja3dr", "Reduction:", choices = immune_objdef$dimrd, 
                          selected = immune_objdef$dimrd[1])) 
      ) 
    ), # End of column (6 space) 
    column( 
      3, actionButton("immune_obja3togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_obja3togL % 2 == 1", 
        selectInput("immune_obja3sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_obja3sub1.ui"), 
        actionButton("immune_obja3sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_obja3sub1non", "Deselect all groups", class = "btn btn-primary") 
      ) 
    ), # End of column (6 space) 
    column( 
      6, actionButton("immune_obja3tog0", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_obja3tog0 % 2 == 1", 
        fluidRow( 
          column( 
            6, sliderInput("immune_obja3siz", "Point size:", 
                           min = 0, max = 4, value = 1.25, step = 0.25), 
            radioButtons("immune_obja3psz", "Plot size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE), 
            radioButtons("immune_obja3fsz", "Font size:", 
                         choices = c("Small", "Medium", "Large"), 
                         selected = "Medium", inline = TRUE) 
          ), 
          column( 
            6, radioButtons("immune_obja3asp", "Aspect ratio:", 
                            choices = c("Square", "Fixed", "Free"), 
                            selected = "Square", inline = TRUE), 
            checkboxInput("immune_obja3txt", "Show axis text", value = FALSE) 
          ) 
        ) 
      ) 
    )  # End of column (6 space) 
  ),   # End of fluidRow (4 space) 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", h4("Assay Expression"), 
      selectInput("immune_obja3inp1", "Feature 1:", choices=NULL) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
              title = "Feature expression to colour cells by", 
              content = c("Select gene to colour cells by gene expression", 
                         paste0("- Feature expression are coloured in a ", 
                                "White-Red colour scheme which can be ", 
                                "changed in the plot controls"))), 
      selectInput("immune_obja3inp2", "Feature 2:", choices=NULL) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Feature expression to colour cells by", 
               content = c("Select gene to colour cells by gene expression", 
                           paste0("- Feature expression are coloured in a ", 
                                  "White-Blue colour scheme which can be ", 
                                  "changed in the plot controls"))), 
      selectInput("immune_obja3ass1", "Assay:", 
                  choices = immune_objdef$assay, 
                  selected = immune_objdef$assay[1]), 
      actionButton("immune_obja3tog1", "Toggle plot controls"), 
      conditionalPanel( 
        condition = "input.immune_obja3tog1 % 2 == 1", 
        radioButtons("immune_obja3col1", "Colour:", 
                     choices = c("Red (Gene1); Blue (Gene2)", 
                                 "Orange (Gene1); Blue (Gene2)", 
                                 "Red (Gene1); Green (Gene2)", 
                                 "Green (Gene1); Blue (Gene2)"), 
                     selected = "Red (Gene1); Blue (Gene2)"), 
        numericInput("immune_obja3min1", "Min cutoff gene 1 (q##):", 
                     min = 0, max = 50, value = 0, step = 1), 
        numericInput("immune_obja3max1", "Max cutoff gene 1 (q##):", 
                     min = 50, max = 100, value = 100, step = 1), 
        numericInput("immune_obja3min2", "Min cutoff gene 2 (q##):", 
                     min = 0, max = 50, value = 0, step = 1), 
        numericInput("immune_obja3max2", "Max cutoff gene 2 (q##):", 
                     min = 50, max = 100, value = 100, step = 1), 
        radioButtons("immune_obja3ord1", "Plot order:", 
                     choices = c("Max-1st", "Min-1st", "Original", "Random"), 
                     selected = "Max-1st", inline = TRUE) 
      ) 
    ), # End of column (6 space) 
    column( 
      6, style="border-right: 2px solid black", 
      uiOutput("immune_obja3oup1.ui"), 
      fluidRow(column(3, downloadButton("immune_obja3oup1.dl", "Download Plot")), 
               column(3, radioButtons("immune_obja3oup1.f", "Plot format:", 
                                      choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
               column(3, numericInput("immune_obja3oup1.h", "Plot height:", 
                                      min = 4, max = 20, value = 8, step = 0.5)), 
               column(3, numericInput("immune_obja3oup1.w", "Plot width:", 
                                      min = 4, max = 20, value = 8, step = 0.5))), 
      br() 
    ), # End of column (6 space) 
    column( 
      3, uiOutput("immune_obja3oup2.ui"), 
      fluidRow(column(6, downloadButton("immune_obja3oup2.dl", "Download Legend")), 
               column(6, radioButtons("immune_obja3oup2.f", "Legend format:", 
                      choices = c("png", "pdf"), selected = "png", inline = TRUE))), 
      br(), h4("Cell numbers"), 
      dataTableOutput("immune_obja3.dt") 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b1: violinplot / boxplot 
tabPanel( 
  HTML("Violinplot / Boxplot"),  
  h4("Cell information / assay expression violin plot / box plot"), 
  "In this tab, users can visualise the assay expression or continuous cell information ",  
  "(e.g. Number of UMIs / module score) across groups of cells (e.g. libary / clusters).", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("immune_objb1inp1", "Cell information (X-axis):", 
                  choices = immune_objconf[grp == TRUE]$UI, 
                  selected = immune_objdef$grp1) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group cells by",  
               content = c("Select categorical cell information to group cells by",  
                           "- Single cells are grouped by this categorical covariate",  
                           "- Plotted as the X-axis of the violin plot / box plot")),  
      selectInput("immune_objb1inp2", "Cell Info / Feature name (Y-axis):", choices=NULL) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell Info / Gene to plot", 
               content = c("Select cell info / feature to plot on Y-axis", 
                           "- Can be continuous cell information (e.g. nUMIs / scores)", 
                           "- Can also be feature expression")), 
      selectInput("immune_objb1ass1", "Data type for Y-axis:", 
                  choices = c("Cell Information", paste0("Assay: ", immune_objdef$assay)), 
                  selected = "Cell Information"), 
      radioButtons("immune_objb1typ", "Plot type:", 
                   choices = c("violin", "boxplot"), 
                   selected = "violin", inline = TRUE), 
      checkboxInput("immune_objb1pts", "Show data points", value = FALSE), 
      actionButton("immune_objb1togT", "Toggle to perform stats test(s)"), 
      conditionalPanel( 
        condition = "input.immune_objb1togT % 2 == 1",  
        radioButtons("immune_objb1stg", "Perform global test:",  
                     choices = c("none","kruskal.test","anova"),  
                     selected = "none"), 
        radioButtons("immune_objb1stp1", "Perform pairwise test:",  
                     choices = c("none","wilcox.test","t.test"),  
                     selected = "none"), 
        textAreaInput("immune_objb1stp2", HTML("Pairwise comparisons to make <br />  
                                             (Separate each pair by new line and <br />  
                                             within each pair using , or ;):"),  
                      height = "150px", value = "none") 
      ), br(), br(),  
      actionButton("immune_objb1togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_objb1togL % 2 == 1", 
        selectInput("immune_objb1sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_objb1sub1.ui"), 
        actionButton("immune_objb1sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_objb1sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("immune_objb1tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_objb1tog % 2 == 1", 
        sliderInput("immune_objb1siz", "Data point size:",  
                    min = 0, max = 4, value = 1.25, step = 0.25),  
        radioButtons("immune_objb1psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("immune_objb1fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        checkboxInput("immune_objb1noi", "Add noise to assay expr", value = TRUE)) 
    ), # End of column (6 space) 
    column(9, uiOutput("immune_objb1oup.ui"), 
    fluidRow(column(2, downloadButton("immune_objb1oup.dl", "Download Plot")), 
             column(2, radioButtons("immune_objb1oup.f", "Plot format:", 
                                    choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
             column(2, numericInput("immune_objb1oup.h", "Plot height:", 
                                    min = 4, max = 20, value = 8, step = 0.5)), 
             column(2, numericInput("immune_objb1oup.w", "Plot width:", 
                                    min = 4, max = 20, value = 10, step = 0.5))), 
    br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b2: Proportion plot 
tabPanel( 
  HTML("Proportion plot"), 
  h4("Proportion / cell numbers across different cell information"), 
  "In this tab, users can visualise the composition of single cells based on one discrete ", 
  "cell information across another discrete cell information. ",  
  "Usage examples include the library or cellcycle composition across clusters.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      selectInput("immune_objb2inp1", "Cell information to plot (X-axis):", 
                  choices = immune_objconf[grp == TRUE]$UI, 
                  selected = immune_objdef$grp2) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to plot cells by",  
               content = c("Select categorical cell information to plot cells by", 
                           "- Plotted as the X-axis of the proportion plot")), 
      selectInput("immune_objb2inp2", "Cell information to group / colour by:", 
                  choices = immune_objconf[grp == TRUE]$UI, 
                  selected = immune_objdef$grp1) %>%  
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group / colour cells by", 
               content = c("Select categorical cell information to group / colour cells by", 
                           "- Proportion / cell numbers are shown in different colours")), 
      radioButtons("immune_objb2typ", "Plot value:", 
                   choices = c("Proportion", "CellNumbers"), 
                   selected = "Proportion", inline = TRUE), 
      checkboxInput("immune_objb2flp", "Flip X/Y", value = FALSE), 
      selectInput("immune_objb2ord1", "Reorder X-axis by which group:", choices=NULL), 
      radioButtons("immune_objb2ord2", "Reorder in which order:", 
                   choices = c("Decreasing", "Increasing"), 
                   selected = "Decreasing", inline = TRUE), 
      actionButton("immune_objb2togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_objb2togL % 2 == 1", 
        selectInput("immune_objb2sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_objb2sub1.ui"), 
        actionButton("immune_objb2sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_objb2sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("immune_objb2tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_objb2tog % 2 == 1", 
        radioButtons("immune_objb2psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("immune_objb2fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE)) 
    ), # End of column (6 space) 
    column(9, uiOutput("immune_objb2oup.ui"), 
           fluidRow(column(2, downloadButton("immune_objb2oup.dl", "Download Plot")), 
                    column(2, radioButtons("immune_objb2oup.f", "Plot format:", 
                                           choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
                    column(2, numericInput("immune_objb2oup.h", "Plot height:", 
                                           min = 4, max = 20, value = 8, step = 0.5)), 
                    column(2, numericInput("immune_objb2oup.w", "Plot width:", 
                                           min = 4, max = 20, value = 10, step = 0.5))), 
           br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
, 
### Tab1.b3: Bubbleplot / Heatmap 
tabPanel( 
  HTML("Bubbleplot / Heatmap"), 
  h4("Gene expression bubbleplot / heatmap"), 
  "In this tab, users can visualise the gene expression patterns of ", 
  "multiple genes grouped by categorical cell information (e.g. library / cluster).", br(), 
  "The normalised expression are averaged, log-transformed and then plotted.", 
  br(),br(), 
  fluidRow( 
    column( 
      3, style="border-right: 2px solid black", 
      textAreaInput("immune_objb3inp", HTML("List of gene names <br /> 
                                        (Max 50 genes, separated <br /> 
                                         by , or ; or newline):"), 
                    height = "250px", 
                    value = paste0(immune_objdef$genes[[1]], collapse = ", ")) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "List of genes to plot on bubbleplot / heatmap", 
               content = c("Input genes to plot", 
                           "- Maximum 50 genes (due to ploting space limitations)", 
                           "- Genes should be separated by comma, semicolon or newline")), 
      selectInput("immune_objb3ass1", "Assay:", 
                  choices = immune_objdef$assay, 
                  selected = immune_objdef$assay[1]), 
      selectInput("immune_objb3grp", "Group by:", 
                  choices = immune_objconf[grp == TRUE]$UI, 
                  selected = immune_objconf[grp == TRUE]$UI[1]) %>% 
        helper(type = "inline", size = "m", fade = TRUE, 
               title = "Cell information to group cells by", 
               content = c("Select categorical cell information to group cells by", 
                           "- Single cells are grouped by this categorical covariate", 
                           "- Plotted as the X-axis of the bubbleplot / heatmap")), 
      radioButtons("immune_objb3plt", "Plot type:", 
                   choices = c("Bubbleplot", "Heatmap"), 
                   selected = "Bubbleplot", inline = TRUE), 
      checkboxInput("immune_objb3scl", "Scale gene expression", value = TRUE), 
      checkboxInput("immune_objb3row", "Cluster rows (genes)", value = TRUE), 
      checkboxInput("immune_objb3col", "Cluster columns (samples)", value = FALSE), 
      sliderInput("immune_objb3max", "Scale.max:", min=1, max=11, value=3, step=0.1), 
      checkboxInput("immune_objb3exp", "expm1 before averaging (check for log-transformed data)",  
                    value = TRUE), 
      br(), 
      actionButton("immune_objb3togL", "Toggle to subset cells"), 
      conditionalPanel( 
        condition = "input.immune_objb3togL % 2 == 1", 
        selectInput("immune_objb3sub1", "Cell information to subset:", 
                    choices = immune_objconf[grp == TRUE]$UI, 
                    selected = immune_objdef$grp1), 
        uiOutput("immune_objb3sub1.ui"), 
        actionButton("immune_objb3sub1all", "Select all groups", class = "btn btn-primary"), 
        actionButton("immune_objb3sub1non", "Deselect all groups", class = "btn btn-primary") 
      ), br(), br(), 
      actionButton("immune_objb3tog", "Toggle graphics controls"), 
      conditionalPanel( 
        condition = "input.immune_objb3tog % 2 == 1", 
        radioButtons("immune_objb3cols", "Colour scheme:", 
                     choices = c("White-Red", "Blue-Yellow-Red", 
                                 "Yellow-Green-Purple"), 
                     selected = "Blue-Yellow-Red"), 
        radioButtons("immune_objb3psz", "Plot size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE), 
        radioButtons("immune_objb3fsz", "Font size:", 
                     choices = c("Small", "Medium", "Large"), 
                     selected = "Medium", inline = TRUE)) 
    ), # End of column (6 space) 
    column(9, h4(htmlOutput("immune_objb3oupTxt")), 
           uiOutput("immune_objb3oup.ui"), 
           fluidRow(column(2, downloadButton("immune_objb3oup.dl", "Download Plot")), 
                    column(2, radioButtons("immune_objb3oup.f", "Plot format:", 
                                           choices = c("png", "pdf"), selected = "png", inline = TRUE)), 
                    column(2, numericInput("immune_objb3oup.h", "Plot height:", 
                                           min = 4, max = 20, value = 10, step = 0.5)), 
                    column(2, numericInput("immune_objb3oup.w", "Plot width:", 
                                           min = 4, max = 20, value = 10, step = 0.5))), 
           br() 
    )  # End of column (6 space) 
  )    # End of fluidRow (4 space) 
)      # End of tab (2 space) 
), 

br(), 
  p("Data source: Leigh et al. (2018) Transcriptomic landscape of the blastema niche in regenerating adult axolotl limbs at single-cell resolution. Nature Communications. https://doi.org/10.1038/s41467-018-07604-0 | Shiny app developed with ShinyCell2.", style = "font-size: 125%;"), 
  p(em("This webpage was made using "), a("ShinyCell2", 
     href = "https://github.com/the-ouyang-lab/ShinyCell2",target="_blank")), 
  br(),br(),br(),br(),br()  
)))  

